### ISSUE TITLE
Docs > Contributing > Code conventions > Is Firebase index updated? 

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#104]
Hi there @gonojuarez or @asimjawad,

there's a section in contributing > code conventions that specifies the Firebase tree index, I'll copy it below but you can check it [here](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=example%20%3A-,Firebase%20index,-%3A). Does this need updating or changing in some way? 

> #!code
index
├── Edad
├── email
├── Fotos
|    ├── nombre_foto
|    └── url_foto
├── FotosUsuario
├── Frases
├── Grupos
├── Juegos
├── Pago
├── Pictos
├── PrimeraUltimaConexion
└── Usuarios

**Comment by asimjawad** [comment]
@VicColombo  For the flutter one, we have changed it. Let me send you that one.

**Comment by VicColombo** [comment]
thanks @asimjawad, you can send it via comment here if that's ok

**Comment by VicColombo** [comment]
hi @asimjawad, do you have anything on this?

**Comment by VicColombo** [comment]
@hectoritr

**Comment by hectoritr** [comment]
Yes, everything changed on Firebase. We will back to you soon

**Comment by lopezjuanma96** [comment]
This is the USER and CAREGIVER structure that we will deploy and test next:

```
{
    "CAREGIVER-ID": {
        "type": "caregiver",
        "settings": {
            "data": {
                "name": "CAREGIVER-NAME",
                "birth-date": "DATE",
                "gender-pref": "CAREGIVER-GENDER-PREF",
                "avatar": {
                    "name": "AVATAR-PICT-LOCAL-NAME",
                    "url": "AVATAR-PICT-REMOTE-URL"
                }
            },
            "language": "APP-LANGUAGE"
        },
        "users": {
            "USER-ID": {
                "alias": "ALIAS-FOR-CAREGIVER-LIST-OF-USERS" 
            }
        }
    },
    "USER-ID": {
        "type": "user",
        "settings": {
            "data": {
                "name": "USER-NAME",
                "birth-date": "DATE",
                "gender-pref": "USER-GENDER-PREF",
                "avatar": {
                    "name": "AVATAR-PICT-LOCAL-NAME",
                    "url": "AVATAR-PICT-REMOTE-URL"
                }
            },
            "language": "APP-LANGUAGE",
            "payment": {
                "paymentDate": "DATE",
                "paymentExpire": "DATE",
                "payment": "BOOLEAN"
            },
            "shortcuts":{
                "games": "BOOLEAN",
                "gallery": "BOOLEAN",
                "shuffle": "BOOLEAN",
                "favs": "BOOLEAN",
                "share": "BOOLEAN"
            }
        },
        "pictos": {
            "LANGUAGE": "DATA"
        },
        "groups": {
            "LANGUAGE": "DATA"
        },
        "phrases": {
            "LANGUAGE": "DATA"
        }
    },
    "default": {
        "pictos": {
            "LANGUAGE": "DATA"
        },
        "groups": {
            "LANGUAGE": "DATA"
        }
    }
}
```

where text in all caps are variables that will change depending on the user and are not necessarily strings but JSON files do not allow text without "". In any case, the structure is up for debate, specially @asimjawad and @emirchus who will make use of it on the app.

**Comment by hectoritr** [comment]
@asimjawad here is the Firebase schema

**Comment by lopezjuanma96** [comment]
latest schema can be found in OTTAA-Project/ottaa_project_flutter#122
