### ISSUE TITLE
Docs > Analytics implementation

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#106]
Hi there @hectoritr or @asimjawad,

The [analytics implementation](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/analytics_implementation.md) section lists 6 kinds of events: 

> * **Talk**  *-Interaction event*
> * **Erase** *- Event related to an erase action*
> * **Delete** *- Event related to deleting a pictogram or group*
> * **Accessibility** *- Event related to accessibility*
> * **Settings**   *- Event related to a setting action*
> * **Pictograms** *- Event related to an add or edit action on a pictogram or group*

and then provides a more complete description of each type in the form of tables. 

1. The table for **delete** is missing, could you provide it?
2. There's an "extra" table for an event called **touch** but there's no short description of it in the list at the beginning. Could you provide that one as well? It should look similar to the ones I posted above.
3. In the tables describing the types of events the actions are in Spanish and the names in English (see example below). Is that ok or would you prefer it to be all in English/all in Spanish?

Accesibility table example:
<h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Accessibility</h4>

Screen | Action | Name of Event
-- | -- | --
Principal | Hablar Con Dispositivo de accesibilidad | Talk with accesibility device
Principal | Hablar Con Barrido de Pantalla | Talk with Screen Scanning
Principal | Galeria Grupos | Group Galery
Galeria Grupos | Boton de Accion | Select Group
Galeria Grupos | Boton de Anterior | Previous Button
Galeria Grupos | Boton de siguiente | Next Button
Galeria Grupos | Boton de Salir | Close Galery Groups
Galeria Pictos | Editar Pictogramas | Edit Pictograms
Galeria Pictos | Boton de Anterior | Previous Button
Galeria Pictos | Boton de Siguiente | Backpress Button

**Comment by VicColombo** [comment]
@hectoritr

**Comment by hectoritr** [comment]
Hey, I'm reviewing the impact of changing the name of the Accessibility keys of name, would be best if everything is in English but we don't want to lose the continuity of the data.

**Comment by asimjawad** [comment]
hey, sorry for not replying on the issues, I was taken by some other work which we are doing and forgot about these issues. I am back now and will be answering these queries on the urgent basis. 
let me go through all of these and will start relying as soon as possible @VicColombo 
and we also have an discord server now...

**Comment by hectoritr** [comment]
Closed with a placeholder until we have the final version of the Code
