### ISSUE TITLE
[Feat]: Link Crowdin for translations & localization

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#111]
### Contact Details

hcosta@ottaaproject.com

### What is this about?

As a developer 

I want to integrate Crowdin platform to automate old and future translations through contributions automatically. 

So that we don't have to worry anymore about localization and translation for different countries. 

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
https://crowdin.com/project/ottaa-project/apps

**Comment by andrii-bodnar** [comment]
👋 

I would recommend the native Crowdin [GitHub Integration](https://store.crowdin.com/github) or the [GitHub Action](https://store.crowdin.com/github-action)

Both of these integrations allow automation of the localization syncing.

**Comment by hectoritr** [comment]
Hi @andrii-bodnar thanks a lot for your comment! We will definitely implement some of those!

**Comment by hectoritr** [comment]
@asimjawad @emirchus we need to rename all string variables in the app that do not comply with the newly documented code convention on variables.
 
https://github.com/OTTAA-Project/ottaa_project_flutter/blob/master/CONTRIBUTING.md#on-variables

After that, I'll start migrating everything to Crowdin.
