### ISSUE TITLE
[Feat]: Profile Settings

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#122]
### What is this about?

As a caregiver, I want to have access to different features designed only to fit my needs. 
So that I can use the app better without dealing with the User features in the middle. 

Check the UI & workflow [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=495%3A1810&t=0TxEn24ejavNmm1M-0)

Action Plan
- [x] profileSettingsScreen
- [x] profileSettingsEditScreen
- [x] profileChooserScreenSelected
- [x] profileHelpScreen
- [x] profileFAQScreen
- [x] profileLinkedAccountScreen
- [x] profileOTTAATipsScreen

**profileSettingsScreen**
Screen to navigate to the different features for the Caregiver, shows its profile image, the logout button, and a list of available features. 

**profileSettingsEditScreen**
Screen to edit the profile information, like photo, mail, name, date of birth

**profileChooserScreenSelected**
Screen to change the type of user. 

**profileHelpScreen**
Screen to help the caregiver sort out problems and contact support. 

**profileFAQScreen**
Screen with frequently asked questions, the text will be provided in Crowdin. 
When the user press the + button, an animation should display the text answering the question. 

**profileLinkedAccountScreen**
Screen to remove linked accounts to this account. 

**profileOTTAATipsScreen**
Screen with Tips, to take the most out of OTTAA, the text will be provided in Crowdin.

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@lopezjuanma96 we need to design the Firebase structure for the caregiver and post it here.

**Comment by asimjawad** [comment]
@hectoritr  need the design for the dialogue which we will show for selecting the dates on the ProfileEditSettingScreen.
Will also mention new things if required here

**Comment by hectoritr** [comment]
Which one? Can you explain a bit about where this dialog should go? I don't understand to ask the designers about it

**Comment by hectoritr** [comment]
@asimjawad Here

**Comment by lopezjuanma96** [comment]
uploading most updated version of the database structure, latest modification is adding an "id" key in users and caregivers object to access hash more easily
![Flutter's New UserStructure drawio](https://user-images.githubusercontent.com/48799361/209971394-c12323db-244d-4003-9c74-c3eebc20538f.png)

**Comment by asimjawad** [comment]
@lopezjuanma96 ok

**Comment by hectoritr** [comment]
UI overflow

- [ ] Fix the UI overflow
- [ ] Store & fetch the data (DoB, Name Changes, etc, Picture)
- [ ] Test before pushing

![Image](https://user-images.githubusercontent.com/12820318/211316314-270d89d5-8667-45e0-b8c2-a44de6ec5fe1.jpeg)

**Comment by lopezjuanma96** [comment]
Quick addition, we included last-connection under "HASH/settings/data" with the millis value for the last connection date

**Comment by lopezjuanma96** [comment]
uploading lasest updates, aside from the ones on the comments, changed the payment values to match the name patterns in the rest of the db

![Flutter's New UserStructure drawio](https://user-images.githubusercontent.com/48799361/211361868-59551b02-f920-4f07-b6e6-af1ce30c7c75.png)
