### ISSUE TITLE
[Feat]: Add/Link Account

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#123]
### What is this about?

As a caregiver, I want to Add or Link a user account to edit and work with.  
So that I don't rely on the user's tablet physically to do so. Also, it has many features to plan the therapy. 

UI & workflow [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=1342%3A2621&t=0TxEn24ejavNmm1M-0)

Action Plan Add
We will wait to develop this part. DO NOT DO THIS WORKFLOW

Action Plan Link
- [x] linkMailScreen
- [x] linkTokenScreen
- [x] create Token backend
- [x] addLinkWaitScreen
- [x] addLinkOkScreen

**linkMailScreen**
The caregiver needs to input an email from a user account, if the email doesn't exists on the database, prompt a message saying that you need to create a User Account on OTTAA first. 

**linkTokenScreen**
With the email from the user, we should look into our database, and if it exists we need to display a temporary token on the user's main screen, as a Notification. If the token matches, we can safely link the account, meaning the user agrees to link the account with the caregiver. 

The token should follow this process. 
<img width="763" alt="Screen Shot 2022-11-22 at 17 29 59" src="https://user-images.githubusercontent.com/12820318/203415022-7c1009b0-f02e-4ea9-93bf-347d3080f90e.png">

The notification should be fired from Firebase to the OS. 

**addLinkWaitScreen**
Very simple splash screen waiting for the validation to happen. 

**addLinkOkScreen**
If fails should go back to linkTokenScreen
If OK, should show a confirmation message and the user profile snippet. 

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@lopezjuanma96 Emir got blocked somehow and is not receiving more emails.

**Comment by lopezjuanma96** [comment]
On it

**Comment by hectoritr** [comment]
After testing I have this action point to complete

- [ ] After succesfully linking is not showing the real User card with real data
- [ ] The linked account is not showing on profileMainScreen
- [ ] Show notification for Link Errors (Already linked, Error Linking, etc) Read documentation about error types

**Comment by hectoritr** [comment]
Final changes @asimjawad:

- [ ] User's last connection shows GMT+0 time, it should use the user's time zone.
- [ ] On profileMainScreen caregiver is not updating the user's last connection time. 
- [ ]

**Comment by hectoritr** [comment]
@emirchus There is an error when throwing ERROR messages in TOKEN, that "Error button" does not dissapear

**Comment by emirchus** [comment]
I got it

**Comment by hectoritr** [comment]
All done! :)
