### ISSUE TITLE
[Docs] > Readme > add DPG and cont. integration 

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#125]
### Contact Details

victoriaacolombo@gmail.com

### What is this about?

As a technical writer, I want to suggest the addition of DPG certificate and continuous integration link to readme in compliance with what was discussed a few weeks ago:

> When OTTAA project gets the DPG certification and/or when continuous integration is a reality, the information should be added to README.md mimicking the Cboard README.md as shown below (backers and sponsors symbols and links will not be added), in the form of linked images. 

A place holder was added on readme file for this issue

![cboard_certificates](https://user-images.githubusercontent.com/29028642/204006663-fcc630a7-7ba7-4de4-a539-8f4c12a460ae.png)

- [x] add DPG certification link + image at beginning of [readme.md](https://github.com/OTTAA-Project/ottaa_project_flutter/blob/master/Readme.md)
- [x] add continuos integration info link + image at beginning of [readme.md](https://github.com/OTTAA-Project/ottaa_project_flutter/blob/master/Readme.md)

### Where do you want to see this implemented?

Chrome (WebApp)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
All done!
