### ISSUE TITLE
[Docs] > revise and merge vitoria_doc_changes 

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#126]
### Contact Details

victoriaacolombo@gmail.com

### What is this about?

**[Victoria Colombo is responsible for this issue]**

This issue is here to track completion of final revision of each technical documentation document and final merge of repo. Once that is done, https://ottaa-project.github.io/docs/welcome can be updated following requests in other issues.

- [x] revise readme & set necessary place_holder
- [x] revise contributing & set necessary place_holder
- [x] revise code of conduct & set necessary place_holder
- [x] revise dartdoc guide & set necessary place_holder
- [x] revise analytics implementations & set necessary place_holder
- [x] revise and finalize FAQs
- [x] upload template with placeholders for product architechture
- [x] final merge of victoria_doc_changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
Done! 💯
