### ISSUE TITLE
[Docs]: components architecture template > diagram needs some explanation 

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#128]
### Contact Details

victoriaacolombo@gmail.com

### What is this about?

Hello @hectoritr or @gonojuarez,

as part of the technical documentation revamp, I'm tackling the components architecture diagram. I intend to leave a blank template that you can fill out in the future when the final architecture is settled on. To build that template I need some clarifications on the existing diagram (see picture below). I'll leave some questions and you can answer them as best as possible in the comments.

![image](https://user-images.githubusercontent.com/29028642/204567232-351ec657-b6bd-42c5-a28b-559034c0e59a.png)
  

- [x] 1. Components are separated in three sections but also by colors. Can you explain if the different colors represent different functions? For example, in backend json, firebase analytics, realtime database, firebase storage, and cloud functions all have the same color. What do these components have in common? Is it only to have them separated from the recommender system and NLG algorithms?

- [x] 2. Can you explain shortly how components interact with each other in terms of what information components receive (and from which other components) and what do they send out? This will be helpful to draw the directional arrows in the diagram.

- [x] 3. This is a bit of a follow up to question 1 so they can be answered together maybe. Can you define each component in one or two words? For example, NLG: algorithm (or language model), realtime database: storage, etc.?

I understand that all these components might not be present in the new diagram but I still would need to know what kind of components would be present and most of how they relate to each other in terms of data flow and/or data processing so I can leave you with a useful template.   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VicColombo** [comment]
Well, I've found three templates that could work, changing names of components and adapting them a bit, of course. They can be either reproduced by hand with a design tool or they can be used on the site I'm linking for each of them (paid, I think).

Option 1 has the differentiation between local and cloud storage/infrastructure, but it would also need more retouching because it's not a three layer diagram like the already existing one. Options 2 and 3 look more like the one you already have but a bit more modern, they however do not offer such a clear differentiation between local and cloud services which would still need to be done with colors. 


[option 1](https://creately.com/diagram/example/TtfLBC0p3QH/architecture-diagram-for-mobile-application):
![image](https://user-images.githubusercontent.com/29028642/204789359-96885859-227b-4faa-a16a-3354362ccd7f.png)

[option 2](https://creately.com/diagram/example/jkc71luu/3-layer-architecture-diagram-horizontal-blocks):
![image](https://user-images.githubusercontent.com/29028642/204790139-20f3a15e-683a-4a18-b06e-d5553e9ec5f2.png)

[option 3](https://creately.com/diagram/example/jkc6hqiu1/3-layer-architecture-diagram-vertical-blocks):

![image](https://user-images.githubusercontent.com/29028642/204790737-5b074fc8-05a8-4da5-ada3-de4c19f10563.png)

**Comment by emirchus** [comment]
I think something like this represents right the architecture
![image](https://user-images.githubusercontent.com/32276305/207060322-1cf245d3-2a86-46d0-bade-aea60b2de19d.png)

**Comment by emirchus** [comment]
A Better view:
![image](https://user-images.githubusercontent.com/32276305/207063625-6575dd86-a1aa-481a-b76a-9780060d4af9.png)

**Comment by hectoritr** [comment]
That's a generic representation of what we are doing, if we put the names on it should be great!
