### ISSUE TITLE
[Bug]: UI fixes

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#160]
### Contact Details

-

### What happened?

A bug happened!

Here are the small fixes I found:

app
- [x] add Icon for Android & Web

_Pageview 1_
- [x] Center onboarding.profile.screen text.
- [x] Translate Omitir

_Pageview 2_
- [x] Translate Anterior
- [x] Translate Omitir
- [x] Translate onbo...home.subtitle

_Pageview 3_
- [x] Center onboarding.customize.title (In Spanish)
- [x] Center onboarding.customize.screen text.
- [x] Translate customize.titlte
- [x] Translate Comenzar

_profileChooseScreen_
- [x] Translate profile.necesita.comunicarse
- [x] Add Highlight when you click one of the options.
- [x] Active Continue button when is highlighted.

_profileMainScreen_
- [x] Fix the Dropdown functionality (One click show dropdown - One click remove the dropdown)
- [x] Remove (Create new account option) for now we are doing only Link to an account

_profileSettingsScreen_
- [x] Fetch name of the user
- [x] Fetch avatar/image from database
- [x] Add Logout functionality

_profileHelpScreen_
- [x] FAQ snippet has a right overflow
- [x] Contact snippet is not working
- [x] Add FAQs
- [x] Fix return button from FAQs

_profileTipsScreen_
- [x] Fix routing to Tips screen.

_profileLinkMailScreen_
- [x] Translate Strings
- [x] Button has shadows

### Version

6.7.x (Beta)

### Where are you seeing the problem on?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emirchus** [comment]
Hi @hectoritr , which icon should we use for the platforms?

**Comment by hectoritr** [comment]
@emirchus is the logo done & ready?

**Comment by hectoritr** [comment]
[IconKitchen-Output.zip](https://github.com/OTTAA-Project/ottaa_project_flutter/files/10343886/IconKitchen-Output.zip)

Logo for Android, iOS & web

**Comment by emirchus** [comment]
The icons are already there
