### ISSUE TITLE
[Feat]: homeGridScreen

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#170]
### What is this about?

As a user I want to search for Pictos using a Tab Layout to search for Pictos So that is easier for me to find what I want.

Design is [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=2419%3A8944&t=EFp2N9IZW40ZWH0h-0)

Action Plan

- [x] Check the settings for Tab or Grid layout
- [x] We need to load all ACTIVE groups in a Grid Layout.
- [x] When the user choose a Group we need to show all Pictos inside the selected Group as a Grid layout
- [x] Use vertical arrows to navigate the Pictos. 

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@emirchus 

You need to show only the ACTIVE Boards for that user on the Grid. Now you are showing everything.

**Comment by emirchus** [comment]
Ready for test
