### ISSUE TITLE
[Feat]: talk feature

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#171]
### What is this about?

As a user I want to see one-by-one highlighted the pictos when talking So that I can understand better whats happening.

The design is [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=2434%3A8686&t=EFp2N9IZW40ZWH0h-0)

Action Plan

- [ ] Check for the setting if ONE-BY-ONE feature is active
- [x] When the user press "Talk" we need to put an overlay over the whole HomeScreen 
- [x] Highlight one picto at a time when the sentence is read outloud by the TTS. 
- [x] If the feature ONE-BY-ONE is disabled you should highlight the whole sentences and read outloud as is.

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
Everything looks very good. Just a few things to adjust.

- [ ] Pictos overlay doesn't line up properly with the Sentece creation line.
- [ ] There is no way to go back to mainScreen ()

**Comment by hectoritr** [comment]
![Image](https://user-images.githubusercontent.com/12820318/217006154-c4f293ac-4d74-4662-975e-1e34a5bade87.png)

**Comment by asimjawad** [comment]
@hectoritr fixed
