### ISSUE TITLE
[Feat]: Settings Screen

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#191]
### What is this about?

As a user, I want a screen for settings so I can customize stuff across the app. 

Design [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=1366%3A6622&t=HaL433qCnbrYLWXh-0)

Action plan: 

- [x] Create Settings screen
- [x] Create MainSettings screen
- [x] Create Accessibility screen
- [x] Create VoiceAndSubtitles screen
- [x] Create Language screen
- [x] Link Settings button in User & Profile Main ("Configuracion") with this screen

**Settings screen**
It's a list with all available settings screen for the user or caregiver

**MainSettings**
Here the user or caregiver can switch between the Board Navigation mode (Tab or Grid layout #170 ). 
Also the user can clear HomeScreen after speaking "Borrar cuando hablar" switch.
The user can select and deselect Home Screen shortcuts. 

**_IMPORTANT_**
OTTAA Labs feature go into Language screen

**Accesbility**
In this screen we will setup all accessibility screen for the app (We will implement the features later)

**Voice & subtitles**
Here the user can customize the TTS output, we should list all available voices in the preferred language. 
Also the user can change the speed of the voice.
Under subtitles
We can customize subtitles (not yet implemented)

**Language** **_IMPORTANT_**
Here we can change the language and locale, for example, if the user chooses Spanish, we should offer all available localizations Colombia, Chile, Argentina, etc. is linked with #99 and Crowdin. 

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asimjawad** [comment]
@hectoritr 
can you add which settings should be uploaded to the firebase and in what structure?
I was thinking if the caregiver changes the setting from his tablet, it needs to be changed on the user's device too

**Comment by lopezjuanma96** [comment]
Here is some initial layout of the settings database:

```json
{
    "data": { //HERE COMPLETE WITH SETUP
        "name": "",
        "avatar": ""
        //.....
    },
    "payment": { //HERE COMPLETE WITH SETUP? OR AFTER
        "payment": false,
        "paymentDate": 0,
        "paymentExpire": 0
    },
    "layout": {
        "clearup": true,
        "shortcuts": {
            "show": true,
            "enabled": {
                "camera": true,
                "favs": true,
                "games": true,
                "history": true,
                "no": true,
                "share": true,
                "yes": true
            }
        },
        "display": "tab" //can be tab or grid
    },
    "accessibility": {
        "device": "none", //can be none, press, scroll, sipuff
        "sweepMode": "elements", //can be elements or sweep
        "sweepSpeed": "mid", //can be slow, mid, fast
        "clickTime": "mid" //can be slow, mid, fast
    },
    "tts": {
        "voice": {
            "name": {
                "es_AR": "default1",
                "en_US": "default2"
            },
            "speed": { //IS IT NECESSARY FOR SPEED TO BE LANGUAGE PREFERENT?
                "es_AR": "mid", //can be slow, mid, fast
                "en_US": "slow" //can be slow, mid, fast
            },
            "mutePict": true
        },
        "subt": {
            "show": true,
            "size": "mid", //can be small, mid, big
            "caps": true
        }
    },
    "language": {
        "language": "es_AR", //HERE COMPLETE WITH SETUP
        "labs": false
    }   
}
```

most of the values will be the default on user creation, except for those commented with "HERE COMPLETE WITH SETUP" that will depend on each specific user configuration - in the case of payment, I did not know if to complete it on creation or if every user will be set up as "no payment" and then complete a premium config -. As for the tts/voice/name (I chose "name" bc it is what Google uses [here](https://cloud.google.com/text-to-speech), on Figma it is "type", that coould work too), I thought they should be differentiated by language, because:
- if a user changes between languages often, they should not have to worry about remembering which voice they were using on each one and have to set it on each change.
- some languages may have more voice offers than others, having only one "name" variable would generate more trouble since the voice "default3" might be active and user will change to a language with only one or two voices and it won't work.
I don't know if this too should be the case for tts/voice/speed, but I thought so.

Another thing, we could normalize all 3-options values like speed and size to the same 3 strings: instead of speed being "slow"/"mid"/"fast" and size being "small"/"mid"/"big", they could all be "low"/"mid"/"high", @asimjawad and @emirchus should decide this based on what would be more useful/confortable for them.

**Comment by emirchus** [comment]
Hi @lopezjuanma96 We did some changes to the model.

Changes:
- Shortcut properties are changed
- Subtitles key

``` json
{
  "data": {
    "name": "",
    "avatar": ""
  },
  "payment": {
    "paymentDate": 0,
    "paymentExpire": 0
  },
  "layout": {
    "clearup": true,
    "shortcuts": {
      "enable": true,
      "camera": true,
      "favs": true,
      "games": true,
      "history": true,
      "no": true,
      "share": true,
      "yes": true
    },
    "display": "tab"
  },
  "accessibility": {
    "device": "none",
    "sweepMode": "elements",
    "clickTime": "mid"
  },
  "tts": {
    "voice": {
      "name": {
        "es_AR": "default1",
        "en_US": "default2"
      },
      "speed": {
        "es_AR": "mid",
        "en_US": "slow"
      },
      "mutePict": true
    },
    "subtitles": {
      "show": true,
      "size": "mid",
      "caps": true
    }
  },
  "language": {
    "language": "es_AR",
    "labs": false
  }
}
```

**Comment by lopezjuanma96** [comment]
@emirchus awesome!

**Comment by asimjawad** [comment]
@emirchus  where?

**Comment by emirchus** [comment]
@asimjawad where what?

**Comment by asimjawad** [comment]
de papa pastre

**Comment by hectoritr** [comment]
@asimjawad Voice&subtitles and Language is missing implementation. 

Voice & subtitles
Here the user can customize the TTS output, we should list all available voices in the preferred language.
Also the user can change the speed of the voice.

Under subtitles NOT IMPLEMENTED
We can customize subtitles (not yet implemented)

- [ ] Fetch all available voices on the device and show them with each voice name.
- [ ] Change TTS speech rate (Slow, Normal, Fast)
- [ ] Change voice and persist user selection. 

Language
Here we can change the language and locale, for example, if the user chooses Spanish, we should offer all available localizations Colombia, Chile, Argentina, etc. linked with https://github.com/OTTAA-Project/ottaa_project_flutter/issues/99 and Crowdin.

- [ ] Fetch available locales and make a chooser, similar to the language chooser. 
- [ ] Change and persist the user selection.

**Comment by asimjawad** [comment]
okie, I need some explanation about some things, let's talk about that today.

**Comment by asimjawad** [comment]
some of the voices work from the tts, some of them don't, there is not a way (yet) to see which one works or which one not without testing them on the user device.

**Comment by hectoritr** [comment]
@asimjawad I need to hear the voice every time you change voices. 

Use a sample text "Esta es la voz que vas a usar en OTTAA" to hear before choosing. 

Also is showing many similar voices, there are duplicated ones
We need to filter the duplicated ones, preferring the locale ones. 
The TTS code looks something like this.
es-ZZ-x-XXX-local
es-ZZ-x-XXX-network

If the XXX code matches filter it out the network one and leave only the local one. 
If it is different show the network ones.


Action plan

- [ ] Speak the sample text when changing voices.
- [ ] Filter available voices.

**Comment by asimjawad** [comment]
I have filtered out the network ones and only kept the local one, and saying out the phrase, "this is a text voice" whenever the user chooses a new voice.
