### ISSUE TITLE
[Bug]: Not fetching Name, BOD properly

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#195]
### Contact Details

- [x] - Fetching first and last name
- [ ] - Fetching DOB
- [x] - Email

### What happened?

A bug happened!

In the profile settings, it shows the whole name, not the Name and Last Name separately. And it is not fetching the Date of Birth from the user properly. 

### Version

6.7.x (Production)

### Where are you seeing the problem?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
This is not working. @asimjawad

**Comment by asimjawad** [comment]
I looked into it and the api too, firebase is not providing the last name for now. We can only fetch the display name, and with that, there are two issues:

1. what if someone does not have a last name in the display name (e.g, Juan)?
2. what if someone has a name like mine (e.g, Muhammad Asim Jawad) or (e.g, Muhammad Asim Bin Jawad) in these 2 given cases bin in not a name, it is a kind of prefix, and in the first one all three are my name and the last name is not included.

**Comment by asimjawad** [comment]
I have added a method to fetch the name and last name, can you test it on multiple accounts for edge cases? @hectoritr

**Comment by hectoritr** [comment]
Sure, will let you know. 
Also, I've seen that now it prompts the permission for Google Places, scope Date of birth, so it is working or still missing some things?

**Comment by hectoritr** [comment]
@asimjawad also, it's not showing the email now. Appears empty.

**Comment by hectoritr** [comment]
@asimjawad what do we need to close this issue?

**Comment by asimjawad** [comment]
we were not fetching the email, due to some DPG or other issue, I will start putting it again.

**Comment by hectoritr** [comment]
Great! Yes, then when we do a review on data protection we handle the data accordingly.
