### ISSUE TITLE
[Feat]: OTTAA Games

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#205]
### What is this about?

As a user, I want to play didactic games so I can play while learning. 

The design for main screen is [here](https://www.figma.com/file/Ro9LZOPdpFcFxCEQbHplmu/Redesign-Ottaa-Project?node-id=2388%3A10844&t=36eOVOFJTPBFinfA-0):

Mutanto should be working on the game screens. 

Action Plan:
- [x] Create Games main screen
- [x] Link Shortcut button with Games
- [x] Create game "What's the Picto?"
- [x] Create game "Match Pictogram"
- [x] Create game "Memory game"
- [x] Create game "Storytelling" 

For game "Storytelling" we will use ChatGPT, so JuanMa will be involved. Ping him when needed. 

_**IMPORTANT:**_ Use issue #26 as a guide for previous details and information about games. 

### Where do you want to see this implemented?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asimjawad** [comment]
Let's talk about this today too.

**Comment by hectoritr** [comment]
@asimjawad Mutanto has just changed the Games thumbnails. FYI

**Comment by asimjawad** [comment]
Thanks for letting me know

**Comment by Da-PC** [comment]
@asimjawad I´ve tested Games, beautifull job. Keep on going!

**Comment by hectoritr** [comment]
For storytelling game: 
The main idea is that the user will be able to add up to 4 pictograms to create their own story. 
For this, they will have to choose first a character for their story. 
- [x] Reuse code from the Boards Tab chooser and filter out a set of boards (People, Animals, Toys, etc)
- [x] They first choose the board, and then the Pictogram

Then, they will choose a modifier. 
- [x] Reuse code from the Boards Tab chooser and filter out a set of boards (Colors, adjectives, feelings)
- [x] They first choose the board, and then the Pictogram

After that, they choose an action
- [x] Reuse code from the Boards Tab chooser and filter out a set of boards (Actions)
- [x] They first choose the board, and then the Pictogram

And finally, they choose a place
- [x] Reuse code from the Boards Tab chooser and filter out a set of boards (Actions)
- [x] They first choose the board, and then the Pictogram

When all this is done, they go to the next screen and create the story @lopezjuanma96 will help here with the prompt. 

The user needs to listen to the story every time they press the "Talk button"

For later features, we will add Save stories and Share stories.

**Comment by Da-PC** [comment]
@asimjawad Feedback from Games:

- [x] Disable the music when reading the story outloud.
- [x] Add a Mute button to the game.
- [x] The game is not choosing the selected Pictograms, it give you different pictograms. 

I chose Amigos, cansado, search, bar
It used Niño, flor, amor

So it´s not the same pictos or the same number of pictos. 

![image](https://user-images.githubusercontent.com/127154933/235173617-cf1ab860-77c3-4eb3-bca6-c23026a8bb29.png)

**Comment by Da-PC** [comment]
@asimjawad 
Things to fix in What´s the Picto
- [x] The game should ask automatically "Whats the picto X? every time shows new pictos"
- [x] When the hint is on throws ERROR 1. you cannot continue using the game
- [x] I´ve disabled the hint and it is still showing.


ERROR 1:
E/flutter (27920): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: A WhatsThePictoProvider was used after being disposed.
E/flutter (27920): Once you have called dispose() on a WhatsThePictoProvider, it can no longer be used.
E/flutter (27920): #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:157:9)
E/flutter (27920): #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:164:6)
E/flutter (27920): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:360:27)
E/flutter (27920): #3      WhatsThePictoProvider.checkAnswerWhatThePicto (package:ottaa_project_flutter/application/providers/whats_the_picto_provider.dart:45:5)
E/flutter (27920): <asynchronous suspension>
E/flutter (27920): #4      WhatsThePictoScreen.build.<anonymous closure> (package:ottaa_project_flutter/presentation/screens/games/whats_the_picto_screen.dart:100:23)
E/flutter (27920): <asynchronous suspension>
E/flutter (27920):

**Comment by Da-PC** [comment]
@asimjawad I can´t use ChatGPT game. 
See the error

[error chatgpt.webm](https://user-images.githubusercontent.com/127154933/235732407-5b6bfc36-498b-4cc7-962e-9b0e433e0538.webm)

**Comment by asimjawad** [comment]
@hectoritr  here is the **ChatGPT** without doing anything.

https://user-images.githubusercontent.com/25550909/235745181-eabe0009-bdb1-4c63-b6e9-e1bcd9e79e36.MP4

**Comment by Da-PC** [comment]
@asimjawad Errors to fix:

- [x] ERROR 1, see on video, the Help button in Whats the Picto is not working. It only switches state when clicking Mute
- [x] ERROR 2: in Match Pictos, add a waiting time when the user choose everything correctly. See Video
- [x] ERROR 3: memory game it is not working. The logic is wrong. It should start again with new pictos and "hide" the new ones again @emirchus See video
- [x] ERROR 4 Memory game it is not choosing the Board/Groups correctly. See video



ERROR 1:

[error mute help.webm](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/611ce04a-c834-4344-bc7e-275d2cbe3ee8)

ERROR 2:
[device-2023-05-09-173543.webm](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/ddd4675b-ce43-4325-8559-c76f1f5462ef)

ERROR 3
[memory game error 3.webm](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/bc45e11f-a639-4c43-9f06-538f5df87807)

ERROR 4:
[memory game.webm](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/7136ea89-050a-49df-9c3d-cc2f81e5c9bc)

**Comment by asimjawad** [comment]
@hectoritr i added my fixes
