### ISSUE TITLE
Check for the setting if ONE-BY-ONE feature is active

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#212]
From #171 Talk Feature, there is a missing Action Point. 

We need to implement the setting ONE-BY-ONE / ALL Pictogram setting, the user should be able to Toggle between the options. 

The Setting should be implemented as a Toggle Setting on MainScreen in "Interacciones" section settings below Talk and Erase "Hablar y Borrar"

**Comment by asimjawad** [comment]
on it

**Comment by hectoritr** [comment]
@asimjawad Please fix #221  so we can close this issue.
