### ISSUE TITLE
[Bug]: Display error when Talking

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#221]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are 

flutter run
Create a long sentece
Speak

### What happened?

The sentence is shown weirdly when the user tries to speak more than 6 pictograms when one on one is off

![image](https://user-images.githubusercontent.com/127154933/226357746-5283caa1-b642-4c85-8645-0ee77ba741b7.png)

### Where are you seeing the problem on?

Android

### Relevant log output

```shell
No relevant console output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
Did you check when ONE-by-ONE is disabled?
