### ISSUE TITLE
[Bug]: Get Link code via Notification

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#223]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are 

When linking 2 accounts the link token email goes to SPAM.

### What happened?

A bug happened!

### Where are you seeing the problem on?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emirchus** [comment]
Ready

**Comment by emirchus** [comment]
@lopezjuanma96 do u have any idea about this?

**Comment by lopezjuanma96** [comment]
Yes it was from the device token error, it shows when the device token provided for the notification does not existed. I just added a catch on the cloud to skip those devices that throw this error and instead  raised a new error if no device tokens were found or all device tokens were invalid. I'll add it to the POSTMAN docs and we can add a message on those cases to ask the user to re-login and see if that updates the device token data.

**Comment by lopezjuanma96** [comment]
@emirchus
Another thing, some devices require permissions for notifications, we should find a way to asks those permissions on login or download
