### ISSUE TITLE
[Bug]: Shortcut not working when linking

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#224]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are

When I´m linking I choose the shortcuts for the user but that does not reflect on the user device. 
Boards is working fine. 

### What happened?

A bug happened!

### Where are you seeing the problem on?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Da-PC** [comment]
@asimjawad this is still happening when first linking an acount

**Comment by asimjawad** [comment]
On it.

**Comment by asimjawad** [comment]
it is fixed, check it and let me know

**Comment by hectoritr** [comment]
Ok will do!

**Comment by hectoritr** [comment]
This is done, but the user is required to close the app and open it again.
