### ISSUE TITLE
[Bug]: Error on Dropdown

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#234]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

Enter User profile

### What happened?

======== Exception caught by widgets library =======================================================
The following assertion was thrown building OTTAADropdown<String>(dirty):
There should be exactly one item with [DropdownButton]'s value: 0. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 892 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

The relevant error-causing widget was: 
  OTTAADropdown<String> OTTAADropdown:file:///C:/Users/Agus/StudioProjects/ottaa_project_flutter/lib/presentation/screens/profile/profile_settings_edit_screen.dart:152:32
When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:892:15)
#3      OTTAADropdown.build (package:ottaa_ui_kit/src/widgets/input/dropdown.dart:26:14)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (7 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#16     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#17     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#19     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#22     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (43 frames)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#67     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#68     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (332 frames)
#400    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#401    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#402    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#403    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#404    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#405    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#406    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#407    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#408    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#409    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#410    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#411    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#412    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#413    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#414    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#415    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#416    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#417    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#418    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#419    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#420    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#421    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#422    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#423    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#424    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#425    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#426    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#427    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#428    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#429    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#430    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#431    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#432    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#433    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#434    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#435    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#436    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#437    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#438    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#439    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#440    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#441    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#442    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#443    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#444    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#445    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#446    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#447    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#448    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#449    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#450    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#451    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#452    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#453    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#454    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#455    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#456    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#457    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#458    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#459    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#460    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#461    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#462    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#463    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#464    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#465    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#466    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#467    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#468    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#469    StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#470    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#471    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#472    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#473    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#474    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#475    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#476    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#477    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#478    StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#479    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#480    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#481    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#482    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#483    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#484    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#485    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#486    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#487    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#488    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#489    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#490    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#491    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#492    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#493    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#494    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#495    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#496    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#497    _invoke (dart:ui/hooks.dart:145:13)
#498    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#499    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

### Where are you seeing the problem on?

Android

### Relevant log output

```shell
======== Exception caught by widgets library =======================================================
The following assertion was thrown building OTTAADropdown<String>(dirty):
There should be exactly one item with [DropdownButton]'s value: 0. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 892 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

The relevant error-causing widget was: 
  OTTAADropdown<String> OTTAADropdown:file:///C:/Users/Agus/StudioProjects/ottaa_project_flutter/lib/presentation/screens/profile/profile_settings_edit_screen.dart:152:32
When the exception was thrown, this was the stack: 
#2      new DropdownButton (package:flutter/src/material/dropdown.dart:892:15)
#3      OTTAADropdown.build (package:ottaa_ui_kit/src/widgets/input/dropdown.dart:26:14)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (7 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#16     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#17     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#19     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#22     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (43 frames)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#67     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#68     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (332 frames)
#400    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#401    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#402    Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#403    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#404    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#405    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#406    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#407    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#408    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#409    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#410    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#411    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#412    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#413    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#414    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#415    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#416    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#417    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#418    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#419    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#420    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#421    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#422    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#423    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#424    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#425    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#426    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#427    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#428    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#429    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#430    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#431    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#432    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#433    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#434    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#435    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#436    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#437    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#438    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#439    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#440    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#441    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#442    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#443    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#444    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#445    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#446    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#447    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#448    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#449    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#450    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#451    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#452    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#453    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#454    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#455    StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#456    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#457    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#458    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#459    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#460    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#461    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#462    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#463    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#464    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#465    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#466    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#467    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#468    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#469    StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#470    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#471    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#472    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#473    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#474    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#475    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#476    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#477    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#478    StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#479    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#480    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#481    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#482    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#483    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#484    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#485    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#486    ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#487    Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#488    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#489    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#490    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#491    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#492    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#493    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#494    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#495    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#496    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#497    _invoke (dart:ui/hooks.dart:145:13)
#498    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#499    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
Is this fixed with the BOD issue?

**Comment by asimjawad** [comment]
yes, there is no longer an error now.
