### ISSUE TITLE
[Bug]: Language defaults to es-AR

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#235]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are flutter clean...pub get...

### What happened?

The mobile is in English, but the app switches to es-AR on the onboarding. Which is not correct.
Also when the device is in es-CL does not work. Always defaults to es-AR. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
When linking in a es_CL it's not showing the linked accounts. Apparently linking only works when the language is in es_AR.

**Comment by hectoritr** [comment]
It's now merged.
