### ISSUE TITLE
[Bug]: YES NO button acting weird

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#240]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are run the app, go into home screen and use it as usual. When I clickt the YES or NO button it speaks it correctly but if I then quicly press YES or NO toggling the previous selection I get a wrong sound. 

It appears to be not working when I press quickly, if I wait a bit it works OK. 

[error si no.webm](https://user-images.githubusercontent.com/127154933/230068812-9cc4ed0a-b963-4bc9-be4f-17ba4b89cda7.webm)

### What happened?

A bug happened!

### Where are you seeing the problem on?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@emirchus is this already fixed?
