### ISSUE TITLE
[Bug]: TTS voice selection not persistant

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#241]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.3 stable Dart  2.19.2

### How are you running it?

My steps are, every time I open the app after closing it. I have to choose the TTS voice again, as it goes back to OS default.

### What happened?

A bug happened!

### Where are you seeing the problem on?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asimjawad** [comment]
As we know, TTS Voices can't be the same over the devices. So, I am going to add a device-based feature that will check if the custom TTS is enabled and made its changes persistent.

**Comment by hectoritr** [comment]
Yes, voices are not the same over different devices. But this error is about not persisting the selected voice, it keeps going back to default, maybe even in a different language. 

So, if my OS is in English and I use OTTAA in Spanish with a specific voice. When I close the app and open it again, I would get an English voice. @asimjawad

**Comment by hectoritr** [comment]
@asimjawad what's missing to close this?

**Comment by asimjawad** [comment]
it is kind of done, will be closing it today.
