### ISSUE TITLE
[Bug]: Web Bugs

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#261]
### Contact Details

-

### Branch name

development

### Flutter & Dart version

web

### How are you running it?

I'm running the app hosted in dev.ottaaproject.com on a MacBook with Chrome.

- [x] Increase the speed of the TTS, all available options are slow.
- [x] es_CO throws an error when choosing. 
- [x] Check how the TTS is fetching the available voices because it's very weird and not following the language.
- [x] #266
- [x] Fix the error when the picto does not have relations with other pictos. 

### What happened?

A bug happened!

### Where are you seeing the problem on?

Chrome (WebApp)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emirchus** [comment]
- The spees was increased
- es_CO we cannot replicate the error, pls be sure that u have the last changes
- Ready
- I need  @asimjawad for check for that :)
- Ready
