### ISSUE TITLE
[Feat]: Back button

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#271]
### Contact Details

You should be able to go back from the home screen to the main screen from ios devices
### What is this about?

User is not able to go back to the Main Screen when they are on the Home Screen

### Where would you like to see this implemented?

It should show a dialog box by long-tapping the yellow indicator from the left top side of the screen and should be able to return to the main screen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [x] implement the dialogue box
- [x] implement the feature
- [x] test it

**Comment by asimjawad** [comment]
@hectoritr  ready to merge
