### ISSUE TITLE
[Feat]: Apple login

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#273]
### What is this about?

As an Apple user, I want to log in using Apple ID So that I can download my app from AppStore.

### Where do you want to see this implemented?

Action Plan

- [x] Add Apple Login to LoginScreen (Guideline 4.8 - Design - Sign in with Apple)
- [x] Add Account Deletion on User Profile Settings (Guideline 5.1.1(v) - Data Collection and Storage)

Sign In Documentation
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple
https://developer.apple.com/sign-in-with-apple/

Account Deletion documentation
https://developer.apple.com/support/offering-account-deletion-in-your-app
https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens

iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hectoritr** [comment]
@asimjawad

**Comment by asimjawad** [comment]
I am on it.

**Comment by asimjawad** [comment]
@hectoritr  do we only need the ios sign in for the ios device or for web and android too
