### ISSUE TITLE
[Bug]: Final issues v1

### ISSUE THREAD

**Issue by Da-PC** [OTTAA-Project/ottaa_project_flutter#284]
### Branch name

development

### Flutter & Dart version

Flutter version 3.7.12 stable Dart  2.19.6

### How are you running it?

My steps are 
-flutter pub get
-flutter packages pub run build_runner build --delete-conflicting-outputs
-flutter run

### What happened?

Things to be solved!

HomeScreen
- [x] When creating a sentence and then deleting multiple time the pictos, it lags and the prediction changes a while after the user finishes pressing the delete picto (we need to find a solution for this)

Games
- [x] Make the Pictos bigger in What´s the picto and Match Picto 
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/e96946d0-4f76-4373-9bb2-d1c054d43a75)

- [x] In ChatGPT game there is an error while loading the available boards to choose from
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/8eb521a9-1828-4686-84b9-e97d47055805)

Edit/Create Picto
- [x] When adding a Picto using "Add Picto" you should bypass the board selector as the user is already inside one board and that can be very confusing. Also, you are highlighting the board with the name of the current board, but maybe you are searching by name because if the user has a board name with the same name it highlights the first appeareance.
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/4afffb4c-9692-4694-80c6-8c99e952d21e)

- [x] When adding a Picto step 5 is repeated, should say "Listo, chequea que todo este correcto"
- [x] If you go back to step 4 and go back to step 5 it duplicates the TAG info
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/85340725-5963-460b-abbd-99e355be6338)
  

Settings
- [x] TTS voices as per this [reply](https://stackoverflow.com/questions/62271974/flutter-tts-text-to-speech-is-it-possible-how-to-get-language-code-for-ios) You will need to filter the voices by name (are supposed to not change), so when the user changes the country you ONLY show the names below.
es-AR (Diego, Isabela)
es-CL (Francisca)
es-CO (Carlos, Jimena, Soledad)
en-US (Ava, Nathan, Albert, Whisper, Jester)
it-IT (Alice, Luca, Paola)

- [x] Add a pop-up when changing voices (only iOS) saying that yuo should download the voice from settings
- [x] Change the Voice N in the chips for the name of the voice (iOS will be i.e Luca, in Android/Web it-IT)

Pictogram/Boards

- [x] In tablet layout make the pictos smaller
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/5764fc74-a682-4e04-92c0-ac0919779d92)

- [x] If you add pictos inside a Board and then go back to ProfileUserMain and close the app, the pictos are lost in the group but the Picto is stored as a Pictogram. (See duplicated UNO pictogram)
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/3d95405f-dfd0-4f77-8c2e-3098a03f879c)
![image](https://github.com/OTTAA-Project/ottaa_project_flutter/assets/127154933/4057fbad-4a22-420a-9bb9-dd7d57c123f7)

### Where are you seeing the problem on?

Chrome (WebApp), Android, iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asimjawad** [comment]
on it
