### ISSUE TITLE
FlutterWeb upload image from gallery

### ISSUE THREAD

**Issue by asimjawad** [OTTAA-Project/ottaa_project_flutter#45]
**Describe the solution you'd like**
On flutter web you can not use the same plugins or methods for uploading and handling the images for firebase storage and showing to the user. The main thing is to find a possible permanent solution and make it works.

**Additional context**
This feature can take more time. because it is not handled in flutter community

**Action Plan**
These tasks need to be done
- [x] load Images to flutter web from gallery
- [x] upload images to firebase storage from flutter web

**Comment by hectoritr** [comment]
@asimjawad did you find "possible permanent solution" for this?

**Comment by asimjawad** [comment]
@hectoritr yeah, the gallery one is permanent now.
