### ISSUE TITLE
Add Language: Portuguese, French

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#66]
**Describe the solution you'd like**
Add 2 languages to the app, based on the growth strategy we need to add Portuguese and French. 

**Action Plan**

- [x] Prepare data
- [x] Add JSON data
- [x] Add Language to dropdown on Settings

**Comment by asimjawad** [comment]
@hectoritr comprendo

**Comment by asimjawad** [comment]
translation.dart is the file which has the all of the strings used in the app.

**Comment by asimjawad** [comment]
@hectoritr 
json files for grupos and pictos

**Comment by hectoritr** [comment]
> translation.dart is the file which has the all of the strings used in the app.

Ok, we will see the way of automating adding a new language.

**Comment by hectoritr** [comment]
> @hectoritr json files for grupos and pictos

Sent to Slack

**Comment by hectoritr** [comment]
> > translation.dart is the file which has the all of the strings used in the app.
> 
> Ok, we will see the way of automating adding a new language.

@lopezjuanma96 We need to check an easy way of doing this.

**Comment by asimjawad** [comment]
the json is in old schema and and no images files are present in it. @hectoritr
