### ISSUE TITLE
Bug: Project name and logo

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#67]
**Describe the bug**
<img width="451" alt="Screen Shot 2022-08-08 at 15 18 15" src="https://user-images.githubusercontent.com/12820318/183486517-3feeb862-2415-49f6-876f-fb5f0c33d68a.png">

<img width="305" alt="Screen Shot 2022-08-08 at 16 07 50" src="https://user-images.githubusercontent.com/12820318/183495138-12542d5b-38f3-4f4c-9bb6-e1dbe5d92d17.png">

We need to add a project logo, so the Flutter icon doesn't show up anymore, also change the project name to display OTTAA Project instead of ottaa_project_flutter. 

**To Reproduce**
1. Go to Login Screen, on Google Sign-in account choose dialog.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android API 27
 - Version v.1.0-bugs & older

**Smartphone (please complete the following information):**
 - Device: all

**Comment by asimjawad** [comment]
Ok, Send me the logo files @hectoritr

**Comment by hectoritr** [comment]
> Ok, Send me the logo files @hectoritr

Sent to Slack

**Comment by hectoritr** [comment]
@asimjawad not showing the logo on Web. 

![WhatsApp Image 2022-08-15 at 6 12 36 PM](https://user-images.githubusercontent.com/12820318/184719693-c7cb3134-f62d-409e-9d8d-41ecbe22ffb9.jpeg)

**Comment by hectoritr** [comment]
[IconKitchen-Output.zip](https://github.com/OTTAA-Project/ottaa_project_flutter/files/10343885/IconKitchen-Output.zip)

Logo Assets
