### ISSUE TITLE
API key exposed. 

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#68]
**Describe the bug**
The Firebase configuration of the project was exposed. 

Check https://github.com/OTTAA-Project/ottaa_project_flutter/blob/20e0e2412c27b530dd37eed7b5c89a78fd68c469/web/index.html to see it. 

We need to rotate the API Key related to the project.

**Comment by asimjawad** [comment]
@hectoritr 
read the accepted answer over here:
https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public
