### ISSUE TITLE
Docs Readme > Resources > Documentation API reference might need updating

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#78]
@gonojuarez  The API Reference or [Documentation](https://ottaaproject.com/javadoc/) link in [README.md](https://github.com/OTTAA-Project/ottaa_project_flutter#readme) refers users to automatic Java doc and might need to be replaced entirely, but I'm not sure. Let me know whatever needs to happen (leave as it is, replace with new doc or delete section) and I'll make the changes.

**Comment by hectoritr** [comment]
@gonojuarez Did you see something about this?

**Comment by VicColombo** [comment]
Hi @gonojuarez, any updates on this?

**Comment by gonojuarez** [comment]
I found information about how to make comments in [Flutter](https://dart.dev/guides/language/effective-dart/documentation).
I suggest reading the following [post ](https://medium.com/codex/flutter-dart-documentation-791371ff2e0f)that explains how to encapsulate the comments as documentation.

**Comment by VicColombo** [comment]
Great, so just to be sure @gonojuarez @hectoritr I'll add a section using this information on how to document on flutter using dartdoc. I believe it's better to just move this section to contributing (right now is in Readme), would you agree? Would someone need to know about flutter documentation if they're not about to contribute?

**Comment by hectoritr** [comment]
Hey @VicColombo yes I agree. Let make a quick section explaining the basics of the dartdoc tool, and we will start commenting the whole code to comply with that. Also, let's add a section that will link to the dartdoc page, same aas the javadoc. 

But for new contributors I think a section on contributing is the way to go.

**Comment by VicColombo** [comment]
Hi there, I have **many** doubts regarding API reference documentation and dartdoc, I'll leave them in two separate comments. 

1. @gonojuarez: I found that using dartdoc for Flutter might imply using a different command to run it, namely instead of just `dart pub get`, either `pub global activate dartdoc` or `flutter pub get` should be run before `dartdoc`. I have documented this [here](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/dartdoc_automatic_documentation.md). 

Is that correct? Do any of you use these commands or are they unnecessary/incorrect?

**Comment by VicColombo** [comment]
2. @hectoritr I'll explain the current structure on code contributions and conventions and my questions below. Bear in mind I'm only quoting the parts of code contributions that have to do with my doubts and have left others out. But you can check the entire section [here](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#code-conventions:~:text=about%20a%20version-,Code%20conventions,-Consistent%20code%20writing):

Contributing > Ways of contributing > as a developer > code conventions:


> - On commenting and documenting code:

>     - Always comment all your classes explaining their purpose and how to implement them if required.
>     - Always document all source code via clear comments.
> - General comments (explains syntax and style)
> - API reference 

Right now the API reference only informs that we're using dartdoc and links to this [guide to using dartdoc](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/dartdoc_automatic_documentation.md)). I would like to add some information to this section:

1. What sort of information will be documented using dartdoc. Will it only be classes and members?
2. Is it correct to say that classes will _always_ be documented into the API reference documentation?
3. When documenting classes developers should include a description of the class, the necessary parameters and any other information? 
4. If there are other elements apart from classes that will be documented via dartdoc, what information should be documented about them?
5. what comments should **not** be included in the API reference


The following sections on code conventions are:

> - [Code duplication](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=reference%20%26%20what%20not%3F**-,On%20code%20duplication,-Do%20not%20copy)
> - [importing libraries](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=On%20importing%20libraries)
> - [indentation](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=Example%20%3A-,On%20indentation,-Switch%20case)
> - [classes](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=or%20else%20if-,On%20classes,-The%20attributes%20of)
> - [variables](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=Example%20%3A-,On%20variables,-Local%20variables%2C%20instance)
> - [constants](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=example%20%3A-,On%20constants,-Constants%20should%20be)

For all of them I've erased the old java examples and just left the original conventions and placeholders for code examples. Besides the fact that I'll be asking for the code examples soon (I'll open up another issue):

6. Are these conventions still ok or does anything need to be updated? 

I think that's all for now. Feel free to add any other requests or comments after checking out the current docs.

**Comment by gonojuarez** [comment]
@VicColombo  That is the correct way to install this package, and that is a chord with the library description used.
I think that information is necessary.
[How to install section](https://pub.dev/packages/dartdoc/install)

**Comment by hectoritr** [comment]
@VicColombo hey!
> 2. @hectoritr I'll explain the current structure on code contributions and conventions and my questions below. Bear in mind I'm only quoting the parts of code contributions that have to do with my doubts and have left others out. But you can check the entire section [here](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#code-conventions:~:text=about%20a%20version-,Code%20conventions,-Consistent%20code%20writing):
> 
> Contributing > Ways of contributing > as a developer > code conventions:
> 
> > * On commenting and documenting code:
> 
> > ```
> > - Always comment all your classes explaining their purpose and how to implement them if required.
> > - Always document all source code via clear comments.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * General comments (explains syntax and style)
> > * API reference
> 
> Right now the API reference only informs that we're using dartdoc and links to this [guide to using dartdoc](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/dartdoc_automatic_documentation.md)). I would like to add some information to this section:
> 
> 1. What sort of information will be documented using dartdoc. Will it only be classes and members?
> 2. Is it correct to say that classes will _always_ be documented into the API reference documentation?
> 3. When documenting classes developers should include a description of the class, the necessary parameters and any other information?
> 4. If there are other elements apart from classes that will be documented via dartdoc, what information should be documented about them?
> 5. what comments should **not** be included in the API reference
> 
> The following sections on code conventions are:
> 
> > * [Code duplication](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=reference%20%26%20what%20not%3F**-,On%20code%20duplication,-Do%20not%20copy)
> > * [importing libraries](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=On%20importing%20libraries)
> > * [indentation](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=Example%20%3A-,On%20indentation,-Switch%20case)
> > * [classes](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=or%20else%20if-,On%20classes,-The%20attributes%20of)
> > * [variables](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=Example%20%3A-,On%20variables,-Local%20variables%2C%20instance)
> > * [constants](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md#Code-conventions:~:text=example%20%3A-,On%20constants,-Constants%20should%20be)
> 
> For all of them I've erased the old java examples and just left the original conventions and placeholders for code examples. Besides the fact that I'll be asking for the code examples soon (I'll open up another issue):
> 
> 6. Are these conventions still ok or does anything need to be updated?
> 
> I think that's all for now. Feel free to add any other requests or comments after checking out the current docs.

1. Dartdoc automatically will create standardized documentation for the whole project, if the code is properly commented. 
2. Yes, it is correct. 
3. Yes, by doing that the documentation will be properly created and useful for the next person reading it .
4. I'll check but it is mainly classes, variables, constants and relationship between classes. 
5. I can't of any example right now. 
6. Convention are OK.  Probably we need to add a convention for branch naming. @emirchus can help with this.

**Comment by emirchus** [comment]
Hello
For branches and commits I prefer to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

In case of a branch I use the type of change it is going to contain with a short description [branching models](https://nvie.com/posts/a-successful-git-branching-model/)
Examples: 
<table>
  <thead>
    <tr>
      <th>Instance</th>
      <th>Branch</th>
      <th>Description, Instructions, Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Stable</td>
      <td>main</td>
      <td>Accepts merges from Working and Hotfixes</td>
    </tr>
    <tr>
      <td>Development</td>
      <td>dev</td>
      <td>Accepts merges from Features/Issues, Fixes and Hotfixes</td>
    </tr>
    <tr>
      <td>Features/Issues</td>
      <td>feat/*</td>
      <td>Always branch off HEAD of Working</td>
    </tr>
    <tr>
      <td>Fixes</td>
      <td>fix/*</td>
      <td>Always branch off HEAD of Working</td>
    </tr>
    <tr>
      <td>Hotfix</td>
      <td>hotfix/*</td>
      <td>Always branch off Stable</td>
    </tr>
  </tbody>
</table>


And for commits I use as specified by conventional commits:

```
feat: allow provided config object to extend other configs

BREAKING CHANGE: 'extends' key in config file is now used for extending other config files
```

**Comment by VicColombo** [comment]
Hey there @emirchus @hectoritr & @gonojuarez I've implemented all changes resulting of your answers and comments, they were really useful! [Contributing](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md) is now closer to completion and I'll be making a PR with the updates today, than you very much!!

PS: If you have any new requests or spot anything you want to change feel free to open up a new issue.
