### ISSUE TITLE
Docs Readme > Resources > Libraries & Tools check for necessary updates  

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#79]
@gonojuarez or @hectoritr Is the list of Libraries and Tools in [README.md](https://github.com/OTTAA-Project/ottaa_project_flutter#readme) up to date? Current ones are: 

Libraries:
- [Volley](https://github.com/google/volley) - Network requests
- [Android-RateThisApp](https://github.com/kobakei/Android-RateThisApp) - App rating
- [Lottie for Android](https://github.com/airbnb/lottie-android) - Dynamic animations
- [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart) - Graphic reports
- [Glide](https://github.com/bumptech/glide) - Image loading
- [Lightweight-Stream-API](https://github.com/aNNiMON/Lightweight-Stream-API) Stream API for Java 7
- [SimpleNLG](https://github.com/simplenlg/simplenlg) - Natural language processing
- [Android Support Library](https://developer.android.com/) - Android (Google) support library

Tools:

- android_dev [Android Studio](https://developer.android.com/studio)

- bit_bucket [Bitbucket](https://bitbucket.org/)

- araasac [Araasac](http://arasaac.org/)

- test_platform [Testproject](http://testproject.io/)

Please let me know if any replacements or additions are needed or if it's ok as it is.

**Comment by hectoritr** [comment]
@asimjawad can you review and update the libraries, widgets, etc the current code uses? Don't forget to add the Pictowidget.

**Comment by asimjawad** [comment]
Ok @hectoritr

**Comment by asimjawad** [comment]
@VicColombo I will be replacing them this week and will let you know.

**Comment by VicColombo** [comment]
great, thanks for the update @asimjawad !

@hectoritr should I leave them as they are in the meanwhile or just leave the titles as place holders and leave the section empty?

**Comment by hectoritr** [comment]
Let's leave it empty until finished

**Comment by hectoritr** [comment]
@asimjawad on this one as well

**Comment by asimjawad** [comment]
I have changed the libraries we are currently using, will be adding more in future because we are thinking about changing somethings in the app.
and sorry for being late...

**Comment by VicColombo** [comment]
HI there @asimjawad, I'm back from my leave. I've tried the link to the new libraries but it doesn't seem to be working, could you re paste it or update it?

**Comment by asimjawad** [comment]
https://github.com/OTTAA-Project/ottaa_project_flutter/blob/5295e86fe60e097df5372c44401d49ebec0274cf/Readme.md

**Comment by VicColombo** [comment]
that's great, I got it! I have a this follow up question now. Since the list is quite extensive compared to the one you had before, I'm considering making it it's own readme file and just linking it to readme.md. Before I do that I'd like to know if some of these libraries could be considered "main libraries" or something like that, that way I'd name a few on the readme file and link the rest. This is purely stylistic and linking them works just as fine, so if there can't really be a "main libraries" list because they're all equally important of if making that list implies more than a few minutes work just let me know and I'll link them on a separate file.

**Comment by asimjawad** [comment]
ok, let me categorically place them then

**Comment by asimjawad** [comment]
https://github.com/OTTAA-Project/ottaa_project_flutter/blob/840533f227b5754166495dbb3241597e541b2dc2/Readme.md
check this one @VicColombo

**Comment by VicColombo** [comment]
that is perfect @asimjawad, thanks! I'll close this issue for now and if any new libraries or tools are added just assign me a new one and I'll update the official readme.
