### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#8]
**Is your feature request related to a problem? Please describe.**
- NO
If YES  please write a clear and concise description of what the problem is. 

**Describe the solution you'd like**
The user should be able to do a short 4-page tutorial that briefly explains the main features of OTTAA. 
All the assets are found in the provided folder. 

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
See attached images.
- [x] Tutorial I
- [x] Tutorial II
- [x] Tutorial III
- [x] Tutorial IV

![Inicio 1](https://user-images.githubusercontent.com/12820318/124981579-1c106d00-e00c-11eb-9ef2-26a4275681b9.png)
![Inicio 2](https://user-images.githubusercontent.com/12820318/124981587-1dda3080-e00c-11eb-90bd-237c955e1902.png)
![Inicio 3](https://user-images.githubusercontent.com/12820318/124981591-1e72c700-e00c-11eb-8499-9951b01d20ba.png)
![Inicio 4](https://user-images.githubusercontent.com/12820318/124981597-1f0b5d80-e00c-11eb-8045-eea53cc5eb5d.png)

**Comment by mal2tin** [comment]
I need the next button with a white background, the ready button and the orange color code.
