### ISSUE TITLE
Docs Readme > Resources > icons from Fluttericons needed?

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#80]
@hectoritr In the Resources section of [Readme.md](https://github.com/OTTAA-Project/ottaa_project_flutter#readme) there's a line stating "added some custom Icons here from the FlutterIcons website", it feels like somtething else is missing or the line is out of place. Could anyone look into this?

**Comment by hectoritr** [comment]
@VicColombo I think we can skip this part and remove it.

**Comment by VicColombo** [comment]
thanks!
