### ISSUE TITLE
Docs Readme request for relevant statistics to add

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#82]
Hello @hectoritr or @gonojuarez,

at the [top](https://github.com/cboard-org/cboard#:~:text=Cboard%20%2D%20AAC%20Communication%20Board%20for%20browsers) of the cboard README.ms there's a series of images displaying relevant statistics about the software (localized, backers, the DPG registry, etc.). Would you like this to be added to the OTTAA flutter README.md as well? If so, I will need the same information or any relevant information you want to feature there.

Thanks,

- [ ] decide wether or not to display relevant statistics/info on readme.md 
- [x] if yes, provide links/info

**Comment by hectoritr** [comment]
When the project is certified as DPG we will add it, also when we implement continuous integration we can put the check. Should we leave the placeholder, or doit later?
We will not add the backers and sponsor badges.

**Comment by VicColombo** [comment]
> 

Ok then, I'm not sure about leaving placeholders since they're just linked images to the certification/status on circleci (see caption below), but it really is up to you. These are the two options, let me know which one you guys prefer:

- [ ] opt. 1: Place holder - (I could leave a "DPG certification pending" and /or "continuous integration pending" message at the beginning of README) 

- [ ] opt. 2: Do it late - I could add a Pending section on the master file and leave a note there to add certification and cont. integration later 

![image](https://user-images.githubusercontent.com/29028642/188930845-b92543f6-5f6c-4d75-8624-d9a2528246f1.png)

**Comment by VicColombo** [comment]
Done too!
