### ISSUE TITLE
Docs Readme > Legal & licenses

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#84]
@hectoritr is this summary for legal and licenses on Readme.md complete? Are there any other licenses that need to be declared here?

> Copyright © 2017-2021, [OTTAA Project](https://ottaa-project.github.io/).
>
> This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3 as published by the Free Software Foundation.
> 
> Code - [GPLv3](https://github.com/cboard-org/cboard/blob/master/LICENSE.txt)
> ARASAAC Symbols - [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by hectoritr** [comment]
Hey, here are my suggestions 

- [ ] Add Global Symbols License as follows
- [ ] Remove the Copyright line. 
- [ ] Add OTTAA Trademark line. 

Global Symbols
Code - [GPLv3](https://github.com/cboard-org/cboard/blob/master/LICENSE.txt)
ARASAAC Symbols - [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)
Global Symbols CIC - [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

OTTAA Trademark line
OTTAA Project &trade; 2016 - 2022
OTTAA's brand assets, texts, logos, icons, designs, names of other OTTAA software, and any other brand features and elements, whether registered or unregistered (“Brand Assets”)—are proprietary assets owned exclusively by OTTAA and its group of companies.

**Comment by VicColombo** [comment]
done!
