### ISSUE TITLE
Create Data Schema for storing Picto, Grupos, Frases

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#85]
**Screenshot of the feature to be developed.**
 

**Describe the solution you'd like**

**Additional context**
Add any other context.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by lopezjuanma96** [comment]
diagram for new structure attached on issue #77

**Comment by asimjawad** [comment]
@hectoritr  closing this issue because we have implemented it
