### ISSUE TITLE
Docs Contributing > What you need to know

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#86]
Hey there, @hectoritr ,

[this section](https://github.com/cboard-org/cboard/blob/master/CONTRIBUTING.md#as-a-developer:~:text=discord.gg/TEH8uxh-,As%20a%20developer,-What%20you%20need) at the beginning of contributing as a developer in the Cboard docs is very useful:

> What you need to know
In order to contribute as a developer, you will need to have a basic understanding of [React](https://facebook.github.io/react/docs/hello-world.html) and probably [Redux](https://egghead.io/courses/getting-started-with-redux), you will also need to be familiar with [Material-UI](https://material-ui.com/).

I would like to replicate this bit of information for OTTAA Contributing, what would you guys say are the basic tools and/or languages for someone wanting to contribute as a developer with OTTAA?

**Comment by asimjawad** [comment]
Hey @VicColombo, I really appreciate you helping us. I will be adding some info here which is required for that like the required experiences and tools and other stuff

**Comment by hectoritr** [comment]
Hey @asimjawad please get back to Vicky on this issue!

**Comment by VicColombo** [comment]
Hi there @asimjawad , any updates on this?

**Comment by asimjawad** [comment]
yes, I am currently writing one down, will be finished today.

**Comment by asimjawad** [comment]
Hi @VicColombo not now exactly, we are shifting the whole architecture and the state management for now and will have to rewrite everything.

**Comment by VicColombo** [comment]
OK. Is it's any help, I'll let the place holder paragraph here and you can just fill in the blanks when you know the exact tools/languages etc.:

> In order to contribute as a developer, you will need to have a basic understanding of _[this/these coding languge/s]_ and _[this/these tool/s (could be a framework, library, platform)]_. We also strongly recommend you be familiar with _[these language/technology that might not be as important as the other two mentioned but is still important]_ .

That's more or less what it should look like, although of course there could be more or less requirements and I can adjust the text for them.

**Comment by VicColombo** [comment]
Hello @asimjawad do you have any updates on this?

**Comment by hectoritr** [comment]
@asimjawad @asimjawad @asimjawad @asimjawad

**Comment by VicColombo** [comment]
@hectoritr

**Comment by hectoritr** [comment]
@asimjawad x 16

**Comment by hectoritr** [comment]
Left as a Placeholder
