### ISSUE TITLE
Docs Contributing > Ways of contributing

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#87]
Hi @hectoritr ,

we need to specify how people can contribute as a translator, manual tester and automation tester. I'll leave some guidance questions here so the answers help me build the section information. In the end, we are trying to mimic [these](https://github.com/cboard-org/cboard/blob/master/CONTRIBUTING.md#as-a-developer:~:text=run%20build.-,As%20a%20translator,-To%20help%20with) Cboard section.

Translators
1. Is there a management platform for OTTAA translations?
2. If not (1), is there an email address or online form to apply to contribute with translations? Someone one could get in touch with?
3. Are there any languages that you're particularly keen on prioritizing?
4. Is there any feature in particular that requires better translation or a proofread and should be prioritized?
5. Are the current languages of OTTAA Arabic, English and Spanish?

Manual tester
1. Do you have any other place apart from github/issues where someone can report the results of their testing? If not I'll just leave directions to the issues section in this repo.
2. Do you guys have any test cases plan or are in need of one? Should we appeal to the contributors to create one?
3. Is there any feature that needs testing and should be prioritized by a contributor?

Automation tester
1. Is there any platform/tool you guys are currently using for automation testing that contributors might use?
2. Same as before, are there any priorities?

That's all I need for now I think, if you prefer it I could move all this questionnaire to the master file, I'm ok either way.

**Comment by hectoritr** [comment]
Automation tester

Is there any platform/tool you guys are currently using for automation testing that contributors might use?
We are implementing a continuous integration workflow, that will be running multiple automated testing. 
Same as before, are there any priorities?
Any experience with CI/CD and automated testing in Dart is very much welcome.

**Comment by hectoritr** [comment]
Manual tester

**1. Do you have any other place apart from github/issues where someone can report the results of their testing? If not I'll just leave directions to the issues section in this repo.**
Any bug or hotfix that results from manual testing should be reported via an Issue using the template for Bug reporting.

**2. Do you guys have any test cases plan or are in need of one? Should we appeal to the contributors to create one?**
Yes, we have test cases for manual testing in the following link
[Link to Test Cases](https://docs.google.com/document/d/1khElUEbtREVsTzwxKmLYfdDYJxCnz0zcNaIraRYaMGs/edit)
Probably we can "enchular" this one. 

**3. Is there any feature that needs testing and should be prioritized by a contributor?**
Overall functionality of the new Flutter version.

**Comment by VicColombo** [comment]
Thank you for all the info here @hectoritr, it was really helpful, this section is now done =)
