### ISSUE TITLE
OTTAA Open Roadmap

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#88]
**Describe the solution you'd like**
As part of UNICEF work plan, we need to develop and implement an Open Product Roadmap. 

**Additional context**
https://markwhen.com/
https://github.com/orgs/github/projects/4247/views/1

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [x] Add link to Open Roadmap to Readme or Contributing
- [x] Create Open Roadmap

**Comment by hectoritr** [comment]
Link to the Project https://github.com/orgs/OTTAA-Project/projects/4

**Comment by VicColombo** [comment]
Hi @hectoritr , I'm back!

Is this https://github.com/orgs/OTTAA-Project/projects/4 the open roadmap? Should I add it to our readme?

**Comment by VicColombo** [comment]
great! I've added the link to readme.md
