### ISSUE TITLE
Add diff. Free/Premium features

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#89]
**Screenshot of the feature to be developed.**
 

**Describe the solution you'd like**

**Additional context**
Add any other context.

**Action Plan**
Add an Action Plan with Checkboxes on key things you have to achieve to complete this task.
- [ ] Task A
- [ ] Task B

**Comment by asimjawad** [comment]
@hectoritr  do you want me to add the basic info in it?

**Comment by hectoritr** [comment]
No, this will be handled by Vic.

**Comment by hectoritr** [comment]
Hi @VicColombo  is this done/left as placeholder? Can we close this issue?
