### ISSUE TITLE
Docs > Contributing > As a developer > Creating models (getting started)

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#90]
Hi @hectoritr,

in the original Readme there's this section called [Creating models](https://github.com/OTTAA-Project/ottaa_project_flutter#:~:text=open%20source%20project.-,Project%20Info,-*%5Bcreating%20models%5D) which will now be moved to Contributing > As a developer. This is the fragment I'm referring to:

### Create models

- run `flutter pub get` to get the dependencies.
- run `flutter pub run build_runner build` to generate the model class code.
- run `flutter run` to run the project.
- run `flutter packages pub run build_runner build --delete-conflicting-outputs` if there are some errors for models building.
- run `flutter build web --release --web-renderer html` for building the project.
- run `flutter deploy` for deploying it on the master.
- run `firebase deploy --only hosting:dev-ottaaproject` for deploying it on dev.
 * [Web Page](https://ottaaproject.com)

I have two  questions about this:

1. Would it be correct to rename it "Create your own models"/ "Create your own version of the app", or something like that?
2. I'd like to remove the website link at the end of the list it but just want to check first if it's there for a particular reason.

**Comment by hectoritr** [comment]
1. Probably a good name for it would be "Setting up you IDE" or something like this @asimjawad what do you think?
2. Yeap remove. 

Also the steps needed are the following
run flutter pub get to get the dependencies.
run flutter pub run build_runner build to generate the model class code.
run flutter run to run the project.
run flutter packages pub run build_runner build --delete-conflicting-outputs if there are some errors for models building.

The other I think can be kept internally

**Comment by asimjawad** [comment]
Sorry for the late reply here, one of my cat was sick.
The creating models section is for [**Json_serializable**](https://pub.dev/packages/json_serializable) and [**json_annotation**](https://pub.dev/packages/json_annotation) plugins, we are handling the **parsing dynamically** and these models/plugins help us in doing that. You can say that this step is one of the **main part** of the process in setting up the app.

**Comment by VicColombo** [comment]
@hectoritr, @asimjawad  thank you both for your replies! (hope the cat is better :cat2:).

1. How about this then?:

>**Get started: setting up your IDE**


> - run `flutter pub get` to get the dependencies.
> - run `flutter pub run build_runner build` to generate the model class code.
> - run `flutter run` to run the project.
> - run `flutter packages pub run build_runner build --delete-conflicting-outputs` if there are some errors for models building.

* I have not included @asimjawad 's explanation of this section but can do it if you think it's a good idea. 

2. As I mentioned before, this section used to be at the beginning of the main README file and is now going to be included in the Contributing doc under "Contributing as a developer", the reason for this change is that I assumed if someone is setting up the app it's because they are developers/want to check or do something to do with code. Could you confirm this intuition or refute it if you think it's better for this section to go back to the README doc?

**Comment by asimjawad** [comment]
The first 3 points from the 1st can be added at the top of the **README**. The reason is that even if someone is not a developer and they want to run it, they can just simply type these commands and do it. In case of a first time built the **4th** command is not required because everything will be building from scratch. 
For the **2nd** point yeah, we can add these there for the developers too. Otherwise they would be going through the code to find the issue.

**Comment by asimjawad** [comment]
people usually reads the document in full capital like **README** first 😂

**Comment by VicColombo** [comment]
Thanks for all the info @asimjawad & @hectoritr! =)
