### ISSUE TITLE
Docs Contributing > as a developer > code contribution > comments 

### ISSUE THREAD

**Issue by VicColombo** [OTTAA-Project/ottaa_project_flutter#92]
Hey there @hectoritr,

in the [Documentation - Comments](https://github.com/VicColombo/ottaa_project_flutter/blob/victoria_doc_changes/CONTRIBUTING.md) section of Contributing people are advised to use java documentation:

> **Comments**
> 
> - Comment documenting the source code are required.
> - Comment a class explaining the purpose of that and how to implements if that required.
> - Comment should be formatted as proper English sentences.
> - use Javadoc documentation.

I think that's now old, can I erase that line?

**Comment by hectoritr** [comment]
Yes, of course! Also those point might need re phrasing.

**Comment by VicColombo** [comment]
Oh yes, I just copied the old ones for reference but they've been re written

**Comment by VicColombo** [comment]
Hi @hectoritr, this was completed back when I last commented but I forgot to close it before leaving, I'm closing it now.
