### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/ottaa_project_flutter#96]
There's a new way of adding the Code of Conduct for Github repos, we can use this one. 

https://github.com/github/roadmap/blob/main/CODE_OF_CONDUCT.md

**Comment by hectoritr** [comment]
@VicColombo

**Comment by VicColombo** [comment]
Hi there @hectoritr, so I've revised the code of conduct it and created it as a new document separated from the contributing (but I still linked it on contributing). But I'm not sure if that's all the changes you wanted, it still has the same structure as before:

- OTTAA Project Open Source Code of Conduct
     - Our core principles
        - Diversity helps us grow
        - Debate enriches us
     - Behavior in accordance with our principles
     - Reporting breaches to the code of conduct

When you say that there's a new way of adding the CoC and you'd like to use the github public roadmap, what exactly do you have in mind? Would you like me to re structure it to make it better fit that template or is it just to keep ir separated from the Contributing?

**Comment by hectoritr** [comment]
No, it was just a comment because I found that way of publishing it on the Github repo. 
If you think the current structure is good, let's keep it that way. Up to you! ;)

**Comment by VicColombo** [comment]
I like that other structure too, I'll tell you what: I'll leave myself a task in Asana to replicate it later but for now, since it is complete and other sections of documentations aren't, I'll leave it as is and get going with other sections.
